DROP TABLE IF EXISTS CSMB_CLIENT CASCADE;

CREATE TABLE CSMB_CLIENT
(
    ID           INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME   VARCHAR(255) NOT NULL,
    LAST_NAME    VARCHAR(255) NOT NULL,
    PHONE_NUMBER VARCHAR(255),
    EMAIL        VARCHAR(255)
);

INSERT INTO CSMB_CLIENT(ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER, EMAIL)
VALUES (1, 'Ivan', 'Ivanov', '1111', 'Ivan@mas.ru') ,
    (2, 'Petya', 'Petrov', '2222', 'Petya@ass.su');

DROP TABLE IF EXISTS CSMB_TARIFF;

CREATE TABLE CSMB_TARIFF
(
    ID   INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    COST FLOAT
);

INSERT INTO CSMB_TARIFF(ID, NAME, COST)
VALUES (1, 'Children', 10.5) ,
(2, 'Old', 7.15);

DROP TABLE IF EXISTS CSMB_CARDS;

CREATE TABLE CSMB_CARDS
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    CLIENT_ID   INT NOT NULL,
    TARIFF      INT NOT NULL,
    CARD_NUMBER VARCHAR(255),
    CONSTRAINT FK_1 FOREIGN KEY (CLIENT_ID) REFERENCES CSMB_CLIENT (ID),
    CONSTRAINT FK_2 FOREIGN KEY (TARIFF) REFERENCES CSMB_TARIFF (ID)
);

INSERT INTO CSMB_CARDS(ID, CLIENT_ID, TARIFF, CARD_NUMBER)
VALUES (1, 1, 1, '11111111') ,
    (2, 2, 2, '22222222'),
(3, 1, 2, '33333333');

DROP TABLE IF EXISTS CSMB_BALANCE;

CREATE TABLE CSMB_BALANCE
(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CARD_ID INT NOT NULL,
    BALANCE FLOAT,
    CONSTRAINT FK_3 FOREIGN KEY (CARD_ID) REFERENCES CSMB_CARDS (ID)
);
INSERT INTO CSMB_BALANCE(ID, CARD_ID, BALANCE)
VALUES (1, 1, 200),
    (2, 2, 500);
